### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OSUANSDNC** [xianlin7/SAMCT#1]
This is really a great job, I have some questions that are not clear, I was running the "train_auto_prompt.py" file and noticed that the "opt.load_path", where the weights are loaded in the Is the weights loaded here the weights that have already been trained in "train.py"? Or is it SAM's original VIT-B

**Comment by xianlin7** [comment]
Thanks for your interest in our SAMCT. The "opt.load_path" loaded in "train_auto_prompt.py" can be the trained weights of SAMCT and the original ViT-B, the former can achieve better performance. 

It should be noted that when using the weights of ViT-B, the encoder needs to be partially unfrozen (Line 63-65 instead of Line 61-62).

**Comment by OSUANSDNC** [comment]
Thanks for your reply.
